### ISSUE TITLE
Polish translation doesn't work.

### ISSUE THREAD

**Issue by WukuWukaCiapanos** [Pietersielie/K2RFAC#5]
Hello, I noticed that you updated your mod and added my translation, but unfortunately, it doesn't work. It seems that I have found a solution because when I go into the folder of your mod and change the name of the translation folder to lowercase "pl" instead of uppercase "PL" for the Polish language, it starts working, and the settings are displayed in Polish in the game. Without this change, the text appears in English.

**Comment by Pietersielie** [comment]
Yeah, I'll fix it later today. Localizations are case sensitive, git folders are not. So it's not quite straightforward to fix.

**Comment by Pietersielie** [comment]
Closed by commit 9deb6ef.
